### PR TITLE
Add directories to pdsdata-sync.sh

### PR DESCRIPTION
**Pull request by matthewtiscareno**
Patching pdsdata-sync.sh so that it doesn't ignore important directories. A more complete fix can be done later.

### CODE REVIEW

**Comment by matthewtiscareno** [comment]
Patching pdsdata-sync.sh so that it doesn't ignore important directories.  A more complete fix can be done later.

**Review by markshowalter — CHANGES_REQUESTED** [review]
Matt--Thanks for catching this. What you are seeing is that this script was written for an older organization of the data volumes, in which "shelves/" and "volinfo/ were directory trees parallel to "holdings/". Now all those directories have been moved inside holdings/ and renamed. I think this is the complete set, but you could check the current holdings directory to see if I missed something:
shelves/info/<volset> -> holdings/_infoshelf/<volset>
shelves/info/archives-<volset> -> holdings/_infoshelf-archives-<volset>
shelves/links/<volset> -> holdings/_infoshelf/<volset>
shelves/index/<volset> -> holdings/_indexshelf-<volset>
volinfo/<volset>.txt -> holdings/_volinfo/<volset>.txt
As a result, your checkin will not do a complete job, in general. Instead, you should revert this line back to its original:
   for voltype in metadata previews calibrated diagrams volumes
and then replace the rsync commands that refer to "shelves".

Also, there does not appear to be a line that rsyncs the _volinfo subdirectory, so that should be added. It should follow the pattern you see in the rsync at line 30, where it includes "$3.txt" but then excludes "*". That way, it will only make sure the selected volset file is in sync, but will not potentially overwrite files related to other volumes.

**Comment by matthewtiscareno** [comment]
Okay, I have redone pdsdata-sync.sh according to your instructions, @markshowalter.  Please take a look.

**Review by markshowalter — APPROVED** [review]
Looks fine. The real test is if it does exactly what you expect when you change a file here or there. You can test by doing a "touch" on a shelf file or volinfo file, which changes the modification date, and then seeing if it copies. It's harmless to change a modification date on one of those files. Don't do that on any of our data files (volumes, previews, metadata, archives-*, or checksums-*), but the script has already been tested for those.

**Pull request merged**
